---
version: '3'
services:
    ttn-locator-frontend:
        image: ghcr.io/bassadin/ttn-locator-frontend:latest
        build: .
        restart: unless-stopped
        ports:
            - '8080:80'
