---
version: '3'
services:
    ttn-locator-backend:
        image: ghcr.io/bassadin/ttn-locator-backend:latest
        build: .
        restart: always
        links:
            - db
        ports:
            - '3000:3000'
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/ttn-locator-backend
    db:
        image: postgis/postgis:15-3.3
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ttn-locator-backend
        restart: always
        ports:
            # PostgreSQL Port
            - '57010:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
    pgadmin:
        container_name: pgadmin4_container
        links:
            - db
        image: dpage/pgadmin4:7
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            # Web Interface
            - '57050:80'
        volumes:
            - pgadmin-data:/var/lib/pgadmin
            - ./pgadmin_server_config/servers.json:/pgadmin4/servers.json
            - ./pgadmin_server_config/pgpass:/pgpass:rw
    ttn-locator-frontend:
        image: ghcr.io/bassadin/ttn-locator-frontend:latest
        build: .
        restart: unless-stopped
        ports:
            - '8080:80'
        environment:
            - VITE_TTNMAPPER_LOCATOR_API_URL=http://ttn-locator-backend:3000
volumes:
    postgres-data:
    pgadmin-data:
