---
version: '3'
services:
    ttn-locator-backend:
        container_name: ttn-locator-backend
        image: ghcr.io/bassadin/ttn-locator-backend:latest
        restart: always
        links:
            - db
        ports:
            - '57100:57100'
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/ttn-locator-backend
            - API_KEY=1234567890
    ttn-locator-frontend:
        container_name: ttn-locator-frontend
        image: ghcr.io/bassadin/ttn-locator-frontend:latest
        build: .
        links:
            - ttn-locator-backend
        ports:
            - '57200:57200'
        environment:
            - TTN_LOCATOR_API_URL=http://localhost:57100/
            - TTN_LOCATOR_API_KEY=1234567890
    db:
        image: postgis/postgis:15-3.3
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ttn-locator-backend
        restart: always
        ports:
            # PostgreSQL Port
            - '57010:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
    pgadmin:
        links:
            - db
        image: dpage/pgadmin4:7
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            # Web Interface
            - '57050:80'
        volumes:
            - pgadmin-data:/var/lib/pgadmin
            - ./pgadmin_server_config/servers.json:/pgadmin4/servers.json
            - ./pgadmin_server_config/pgpass:/pgpass:rw
volumes:
    postgres-data:
    pgadmin-data:
